ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"

repos:
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.3.0
  #   hooks:
  #     - id: codespell
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      # - id: check-yaml
      # - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.18.0"
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==22.12.0
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0 # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.3
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix", "--show-fixes"]
      # Run the formatter.
      - id: ruff-format
